language: rust
rust: 
  - stable
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo update
  - cargo test
  - cargo fmt -- --check
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin &&
    cargo tarpaulin --no-count --skip-clean --out Xml &&
    bash <(curl -s https://codecov.io/bash)
  fi