language: rust
rust: 
  - stable
script:
  - cargo clean
  - cargo build 
  - cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin &&
    cargo tarpaulin --no-count --skip-clean --out Xml &&
    bash <(curl -s https://codecov.io/bash)
  fi