language: rust
cache: cargo
rust: 
  - stable
  - beta 
  - nightly
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo clean
  - cargo clippy -- -D warnings
  - cargo update
  - cargo test -- --test-threads=1
  - cargo fmt -- --check
